name: Build Flutter Apps

on:
  - push
  - pull_request

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          # always use --export-options-plist=ios/GithubActionsExportOptions.plist
          build-cmd: flutter build ipa --release --flavor dev --export-options-plist=ios/GithubActionsExportOptions.plist
          certificate-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.IOS_BUILD_CERTIFICATE_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.IOS_MOBILE_PROVISIONING_PROFILE_BASE64 }}
          keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}

      - name: Archive IPA
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          # Try running the build locally with the build command to be sure of this path
          path: build/ios/ipa/App-dev.ipa

  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Build App Bundle
        run: flutter build appbundle
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: |
            build/app/outputs/flutter-apk/app-release.apk
      - name: Upload Android Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bundle
          path: |
            build/app/outputs/bundle/release/app-release.aab
