name: Build Flutter Apps

on:
  - push
  - pull_request

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - name: Build iOS
        run: flutter build ipa --release --no-codesign
      - name: Upload iOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            **/*.ipa

  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Build App Bundle
        run: flutter build appbundle
      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            **/*.apk
            **/*.aab
