name: Build Flutter Apps

on:
  - push
  - pull_request

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      - name: Package as unsigned IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.zip Payload
          mv Runner.zip Runner.ipa
      - name: Upload iOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IPA
          path: |
            Runner.ipa

  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Build App Bundle
        run: flutter build appbundle
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: |
            build/app/outputs/flutter-apk/app-release.apk
      - name: Upload Android Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bundle
          path: |
            build/app/outputs/bundle/release/app-release.aab
