name: Build Flutter Apps

on:
  - push

jobs:
  build_ios:
    runs-on: macos-latest
    steps:

      - name: secrets
        run: |
          echo "certificate-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}"
          echo "certificate-password: ${{ secrets.IOS_BUILD_CERTIFICATE_PASSWORD }}"
          echo "provisioning-profile-base64: ${{ secrets.IOS_MOBILE_PROVISIONING_PROFILE_BASE64 }}"
          echo "keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}"
